include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

build-docker-image:
  variables:
    IMAGE_NAME: nvidia/gpu-driver-container
    # Expected tag is <major>.<minor>.<patch>-<kernel version>-<distro>
    # Example: 570-6.8.0-1032-aws-ubuntu22.04
    EXTRA_ARGS: --build-arg=VERSION=${CI_COMMIT_TAG} --file=precompiled.Dockerfile
  extends: .build-docker-image

sync-gpu-driver-tags:
  stage: release
  rules:
    - if: $CI_COMMIT_BRANCH == "datadog" && $CI_PIPELINE_SOURCE == "schedule"
      when: always
    - when: never
  tags: ["arch:amd64"]
  image: registry.ddbuild.io/ci/compute-delivery@sha256:cf146746871f06c47a9861371fa2b7c4f58cf346dc83db740b61cc6cdaa0230b
  parallel:
    # See supported driver branches here: https://endoflife.date/nvidia
    matrix:
      - DRIVER_BRANCH: 580
  variables:
    KERNEL_MAJOR: 6.8.0
    DISTRIBUTION: ubuntu22.04
    GITHUB_REPO: DataDog/gpu-driver-container
    GITHUB_ACTOR: "datadog-compute-robot"
    GITHUB_TOKEN_FILE: /tmp/github_token
    GOTOOLCHAIN: auto
  id_tokens:
    DDOCTOSTS_ID_TOKEN:
      aud: dd-octo-sts
  before_script:
    - dd-octo-sts version
    - dd-octo-sts debug --scope "${GITHUB_REPO}" --policy gpu-driver-tags
    - dd-octo-sts token --scope "${GITHUB_REPO}" --policy gpu-driver-tags > $GITHUB_TOKEN_FILE
    - export GITHUB_TOKEN=$(cat $GITHUB_TOKEN_FILE)
    - git config --global user.name "${GITHUB_ACTOR}"
    - git config --global user.email "team-compute@datadoghq.com"
    - git config --global url."https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/DataDog".insteadOf "https://github.com/DataDog"
  after_script:
    - dd-octo-sts revoke -t $(cat $GITHUB_TOKEN_FILE)
  script:
    - |
      set -euo pipefail
      echo "Starting GPU driver tags sync process..."

      # Set up github repo
      git clone "https://github.com/${GITHUB_REPO}" ./work && cd ./work
      git remote set-url origin "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git"
      git switch datadog

      echo "Fetching upstream tags..."
      TAG_LIST=$(git tag -l)
      echo $TAG_LIST

      # Find available kernel versions to build
      cd find-driver-version
      go mod download
      go build .
      AVAILABLE_KERNEL_VERSIONS=$(./find-driver-version -d "$DRIVER_BRANCH" -s "$KERNEL_MAJOR" | cut -d' ' -f1)
      cd ..

      echo "$AVAILABLE_KERNEL_VERSIONS" | while read -r kernel_version; do
        TAG="$DRIVER_BRANCH-$kernel_version-$DISTRIBUTION"

        echo "Checking existence of tag: $TAG"
        if echo $TAG_LIST | grep -q "$TAG"; then
          echo "✅ Tag $TAG already exists, skipping it"
        else
          echo "⚠️ Tag $TAG was not found"
          git tag "$TAG"
          git push origin tag "$TAG"
          echo "Tag $TAG was successfully pushed"
        fi
      done

