include: https://gitlab-templates.ddbuild.io/compute-delivery/v2/compute-delivery.yml

build-docker-image:
  variables:
    IMAGE_NAME: nvidia/gpu-driver-container
    # Expected tag is <major>.<minor>.<patch>-<kernel version>-<distro>
    # Example: 570.133.20-6.8.0-1032-aws-ubuntu22.04
    EXTRA_ARGS: --build-arg=VERSION=${CI_COMMIT_TAG} --file=precompiled.Dockerfile
  extends: .build-docker-image
